beard_paths:
  - beards/
  - integration_test_beards/

beards:
  - debugbeard
  - different_name_inside
  - oldstyle_beard

stache_paths: 
  - moustaches

staches:
  - postcats

db_url: sqlite:///skybeard-2.db
db_bin_path: ./db_binary_entries

admins:
  [
  ]

host: 0.0.0.0
port: 8000
